import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthRouter from "@AuthProvider/AuthRouter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} sans antialiased`}
      >
        <AuthRouter>{children}</AuthRouter>
      </body>
    </html>
  );
}
